export const LIST_OF_TEAMMATES = 'LIST_OF_TEAMMATES';
export const ADD_TEAMMATE = 'ADD_TEAMMATE';
export const UPDATE_TEAMMATE = 'UPDATE_TEAMMATE';
export const UPDATE_TEAMMATES = 'UPDATE_TEAMMATES';
export const DELETE_TEAMMATE = 'DELETE_TEAMMATE';

export const LOAD_PROJECT = 'LOAD_PROJECT';

export const LIST_OF_PAIRING_BOARDS = 'LIST_OF_PAIRING_BOARDS';
export const ADD_PAIRING_BOARD = 'ADD_PAIRING_BOARD';
export const DELETE_PAIRING_BOARD = 'DELETE_PAIRING_BOARD';
export const UPDATE_PAIRING_BOARD = 'UPDATE_PAIRING_BOARD';
export const REMOVE_TEAMMATE_FROM_PAIRING_BOARD = 'REMOVE_TEAMMATE_FROM_PAIRING_BOARD';