export const LIST_OF_TEAMMATES = 'LIST_OF_TEAMMATES';
export const ADD_TEAMMATE = 'ADD_TEAMMATE';
export const LIST_OF_PAIRING_BOARDS = 'LIST_OF_PAIRING_BOARDS';
export const ADD_PAIRING_BOARD = 'ADD_PAIRING_BOARD';